name:                renju
version:             1.0
github:              "sergey-jr/renju"
license:             BSD3
author:              "Sergey Bakaleynik"
maintainer:          "s.jr.bakaleynyk@gmail.com"
copyright:           "2021 Innopolis University"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sergey-jr/renju#readme>

custom-setup:
  dependencies:
  - base
  - Cabal
  - cabal-doctest >=1.0.2 && <1.1

ghc-options:
- -Wall -fno-warn-type-defaults

dependencies:
- base >= 4.7 && < 5
- gloss
- matrix
- vector
- directory

library:
  source-dirs: src

executables:
  renju:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - renju

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-project
    - hspec
    - HUnit
    - QuickCheck

  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
    - base
    - doctest
    - Glob
    - QuickCheck
    - template-haskell
